# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_rt.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1096, 563)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        Dialog.setFont(font)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(440, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 440, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.ASRText = QtWidgets.QTextEdit(Dialog)
        self.ASRText.setGeometry(QtCore.QRect(110, 400, 681, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.ASRText.setFont(font)
        self.ASRText.setObjectName("ASRText")
        self.ExitButton = QtWidgets.QPushButton(Dialog)
        self.ExitButton.setGeometry(QtCore.QRect(950, 500, 131, 41))
        self.ExitButton.setObjectName("ExitButton")
        self.label4 = QtWidgets.QLabel(Dialog)
        self.label4.setGeometry(QtCore.QRect(820, 90, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.label4.setFont(font)
        self.label4.setObjectName("label4")
        self.pstate = QtWidgets.QLabel(Dialog)
        self.pstate.setGeometry(QtCore.QRect(940, 90, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.pstate.setFont(font)
        self.pstate.setObjectName("pstate")
        self.ModalityCBox = QtWidgets.QComboBox(Dialog)
        self.ModalityCBox.setGeometry(QtCore.QRect(950, 30, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ModalityCBox.setFont(font)
        self.ModalityCBox.setObjectName("ModalityCBox")
        self.ModalityCBox.addItem("")
        self.ModalityCBox.setItemText(0, "")
        self.ModalityCBox.addItem("")
        self.ModalityCBox.addItem("")
        self.ModalityCBox.addItem("")
        self.label4_2 = QtWidgets.QLabel(Dialog)
        self.label4_2.setGeometry(QtCore.QRect(830, 30, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.label4_2.setFont(font)
        self.label4_2.setObjectName("label4_2")
        self.camera_label = QtWidgets.QLabel(Dialog)
        self.camera_label.setGeometry(QtCore.QRect(40, 60, 341, 241))
        self.camera_label.setText("")
        self.camera_label.setObjectName("camera_label")
        self.Record_Button = QtWidgets.QPushButton(Dialog)
        self.Record_Button.setGeometry(QtCore.QRect(820, 160, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.Record_Button.setFont(font)
        self.Record_Button.setObjectName("Record_Button")
        self.Lip_label = QtWidgets.QLabel(Dialog)
        self.Lip_label.setGeometry(QtCore.QRect(440, 60, 351, 241))
        self.Lip_label.setText("")
        self.Lip_label.setObjectName("Lip_label")
        self.timeLabel = QtWidgets.QLabel(Dialog)
        self.timeLabel.setGeometry(QtCore.QRect(990, 170, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.timeLabel.setFont(font)
        self.timeLabel.setObjectName("timeLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Video"))
        self.label_2.setText(_translate("Dialog", "Lip Motion"))
        self.label_3.setText(_translate("Dialog", "AVSR Result :"))
        self.ExitButton.setText(_translate("Dialog", "Exit"))
        self.label4.setText(_translate("Dialog", "Process State :"))
        self.pstate.setText(_translate("Dialog", "請選擇Modality"))
        self.ModalityCBox.setItemText(1, _translate("Dialog", "audiovisual"))
        self.ModalityCBox.setItemText(2, _translate("Dialog", "audio"))
        self.ModalityCBox.setItemText(3, _translate("Dialog", "video"))
        self.label4_2.setText(_translate("Dialog", "Modality:"))
        self.Record_Button.setText(_translate("Dialog", "Start Record"))
        self.timeLabel.setText(_translate("Dialog", "00:00"))

